### ISSUE TITLE
The product selector styling should match the following design

### ISSUE THREAD

**Issue by ifyio** [Financial-Times/next-product-selector#13]
![ftr213-psp-barrier-v1](https://cloud.githubusercontent.com/assets/675909/9324362/66362a86-4581-11e5-96e5-052a4fcfe9a4.png)

The notable difference are as follows:
* The `SELECT` buttons
* The indentation of bullet points
* The footer

**Comment by ifyio** [comment]
@SarahHornsey, I have created this issue to track the related design work.

**Comment by commuterjoy** [comment]
Old. Done?
